# These environment variables must be set in CircleCI UI
# Make sure to set 'Pass secrets to builds from forked pull requests'
# to OFF in circleci's UI
#
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
#

version: 2
jobs:
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install docere
      - run:
          name: Test that docere can render the content
          command: ./script/render.sh

  deploy:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: pip install docere awscli
      - run:
          name: Render the content using docere
          command: ./script/render.sh
      - run:
          name: Upload to s3
          command: |
            # Upload content to net-mozaws-data-us-west-2-data-rtmo
            aws s3 cp site/ s3://net-mozaws-data-us-west-2-data-rtmo/ --recursive


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: master

      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              only: master

